name: deepec
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - diamond=0.9.24
  - pip=19.0.3
  - tensorflow=1.5.0
  - pip:
    - numpy==1.16.2
    - biopython==1.70
    - h5py==2.7.1
    - keras==2.1.6
    - markdown==2.6.11
    - mock==2.0.0
    - pandas==0.19.2
    - scikit-learn==0.19.0
    - scipy==1.1.0
    - sklearn==0.0    